# This workflow is a demo of how to use the Gihub Actions workflow steps for SignPath. For a complete documentation, 
# view https://github.com/SignPath/github-actions

name: build-and-sign
run-name: Demo workflow signing with SignPath
on: 
  push:
  pull_request:
  schedule:
    - cron:  '30 3 * * *' # every day at 3:30am UTC
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build_and_sign:
    runs-on: windows-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build
      run: ./src/Build.ps1

    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940 # v1.0.0
      with:
        subject-path: .\_BuildResult-unsigned\DemoExample.msi

    - name: create SBOM
      run: ./sbom/Create-SBOM.ps1

    - uses: actions/attest-sbom@v1
      with:
        subject-path: .\_BuildResult-unsigned\DemoExample.msi
        sbom-path: .\_BuildResult-unsigned\bom.xml

    - name: upload-unsigned-artifact
      uses: actions/upload-artifact@v4
      with:
        name: "demo-application-unsigned" 
        if-no-files-found: error
        path: |
          .\_BuildResult-unsigned\DemoExample.msi
          .\_BuildResult-unsigned\bom.xml

    - name: sign
      uses: signpath/github-action-submit-signing-request@v0.3
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: '${{ vars.SIGNPATH_ORGANIZATION_ID }}'
        project-slug: 'Demo_Application'
        signing-policy-slug:  ${{ github.ref == 'refs/heads/main' && 'release-signing' || 'test-signing' }}
        github-artifact-name:  "demo-application-unsigned"
        wait-for-completion: true
        output-artifact-directory: 'demo-application-signed'
    
    - name: upload-signed-artifact
      uses: actions/upload-artifact@v4
      with:
        name: "demo-application-signed" 
        path: "demo-application-signed"
        if-no-files-found: error
